### ISSUE TITLE
Support for animated collision boxes

### ISSUE THREAD

**Issue by Banbury** [Banbury/UnitySpritesAndBones#18]
Many sprite animation tools allow collision boxes that can be animated on a frame by frame basis.

http://www.youtube.com/watch?feature=player_embedded&v=FFQYUtAWZXs

**Comment by tavotavotavo** [comment]
Hey How are you doing?

I'm very interested on this project and probably use it to make the animations of a platformer game I'm making.

I was looking exactly for what this issue is pointing, are you planning on continuing this job? I'm a c# programmer and I could help you to build this functionality if it isnt done yet.

Regards!

**Comment by Banbury** [comment]
Currently, I'm not working on Sprites And Bones. If you're interested in doing some work, feel free to do so.
Sprites And Bones is open source. The more people are working with it, the happier I am :).
